ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS engraving_area_x NUMERIC DEFAULT 50,
ADD COLUMN IF NOT EXISTS engraving_area_y NUMERIC DEFAULT 50,
ADD COLUMN IF NOT EXISTS engraving_area_width NUMERIC DEFAULT 20,
ADD COLUMN IF NOT EXISTS engraving_area_height NUMERIC DEFAULT 10;