ALTER TABLE public.products 
ADD COLUMN IF NOT EXISTS engraving_start_x NUMERIC DEFAULT 30,
ADD COLUMN IF NOT EXISTS engraving_start_y NUMERIC DEFAULT 45,
ADD COLUMN IF NOT EXISTS engraving_end_x NUMERIC DEFAULT 60,
ADD COLUMN IF NOT EXISTS engraving_end_y NUMERIC DEFAULT 40;